import type { Metadata } from "next";
import { Geist, Geist_Mono, Manrope, Fira_Mono } from "next/font/google";

import { ThemeProvider } from "next-themes";

import "./globals.css";
import Nav from "@/components/sections/nav";

const man = Manrope({
  variable: "--font-man",
  subsets: ["latin"],
});

const mono = Fira_Mono({
  variable: "--font-mono",
  weight: ["400", "500", "700", "400", "500", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hey There.. Its Joshua.",
  authors: [
    {
      name: "Joshua Idele",
      url: "https://joshscriptz.vercel.app",
    },
  ],
  creator: "Joshua Idele",
  keywords: [
    "Joshua Idele",
    "Joshua",
    "Idele",
    "Portfolio",
    "Web Developer",
    "Software Engineer",
    "Full Stack Developer",
    "Next.js",
    "React.js",
    "JavaScript",
    "TypeScript",
  ],
  openGraph: {
    title: "Hey There.. Its me, Joshua.",
    description: "Portfolio of Joshua Idele, a Blockchain Developer and Software Engineer.",
    url: "https://joshscriptz.vercel.app",
    siteName: "Joshua Idele",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${man.className} scrollbar scroll-smooth bg-gradient-to-b from-neutral-200 to-white dark:from-neutral-950 dark:to-neutral-900`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <Nav />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
